name: Tarea de Despliegue

on:
  push:
    branches:
      - jongox

jobs:
  deploy:
    name: Trabajo de Despliegue
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el codigo mas reciente
        uses: actions/checkout@v4

      - name: Sincronizar archivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOSTING }}
          username: ${{ secrets.FTP_USUARNAME }}
          password: ${{ secrets.FTP_PASSW }}
          server-dir: ${{ secrets.FTP_WWW }}
          protocol: ftps
          timeout: 86400000
          log-level: standard
          exclude: |
            .git/**
            .github/**
            config/local.php
            database/**
            .env
            README.md


            